### ISSUE TITLE
ImportError: cannot import name 'unregisterUtility' from 'zope.component'

### ISSUE THREAD

**Issue by Buvaneshts** [zopefoundation/Products.SQLAlchemyDA#19]
Hi,

The above mentioned error is resolved. I am providing the reference 
https://github.com/zopefoundation/Products.SQLAlchemyDA/commit/6bbfd02d69f9f864854a76741ddf4e7caaa11ba7,

I cannot see the changes in any tag that is released, any update on when i can get the changes in Products.SQLAlchemyDA,
as this changes is breaking some functionality of my application

**Comment by dataflake** [comment]
Release 2.1 is now published.

**Comment by Buvaneshts** [comment]
Thank you
